---
resources:
- name: concourse-gp
  type: git
  icon: github
  check_every: 1m
  source:
    uri: https://github.com/liwidev/concourse-test
- name: team-a
  type: git
  icon: github
  check_every: 1m
  source:
    uri: https://github.com/Liwidev/concourse-group-a

jobs:
# update this pipeline before updating child pipelines
- name: set-self
  public: true
  plan:
  - get: team-a
    trigger: true
  - set_pipeline: self
    file: team-a/set-pipelines.yml

- name: set-example-pipelines
  public: true
  plan:
  - get: team-a
    trigger: true
    passed: [set-self]
  - get: concourse-gp
  - set_pipeline: ms-1-node
    file: concourse-gp/gp-pipelines/node.yml
  - set_pipeline: ms-1-java
    file: concourse-gp/gp-pipelines/java.yml
