---
resources:
- name: concourse-examples
  type: git
  icon: github
  check_every: 1m
  source:
    uri: https://github.com/liwidev/concourse-test

jobs:
# update this pipeline before updating child pipelines
- name: set-self
  public: true
  plan:
  - get: concourse-examples
    trigger: true
  - set_pipeline: self
    file: concourse-examples/pipelines/set-pipelines.yml

- name: set-example-pipelines
  public: true
  plan:
  - get: concourse-examples
    trigger: true
    passed: [set-self]
  - set_pipeline: job
    file: concourse-examples/pipelines/hello-world.yml
  - set_pipeline: java
    file: concourse-examples/pipelines/java.yml
